### ISSUE TITLE
HBDM Swap API docs still reflect Futures Contracts related values in the example JSON fields to the right

### ISSUE THREAD

**Issue by ebenali** [hbdmapi/huobi_swap_Cpp#1]
* https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#query-trigger-order-open-orders
 specifies `contract_type | string | true | Contract Type` but the example to the right has no such field.

* https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#place-trigger-order : same

* https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#subscribe-order-data-sub : the example to the right shows a snippet JSON with `contract_code` and `contract_type` set to `BTC200626` and `quarter`, respectively

**Comment by foonsun** [comment]
The issue has been moved to the Python issue zone.
