### ISSUE TITLE
example of order

### ISSUE THREAD

**Issue by 18728476237** [hbdmapi/huobi_swap_Cpp#2]
请给个c++ 币本位永续合约的下单demo。目前你们的demo的example中没有下单的代码示例。

**Comment by iohannes-long** [comment]
这个项目中，下单还没实现，目前需要使用者自己实现。可以参考另一个u永续的项目https://github.com/hbdmapi/huobi_futures_Cpp/blob/master/test/restful_order_test.hpp

**Comment by 18728476237** [comment]
谢谢



---Original---

**Comment by 18728476237** [comment]
你好！我基于huobi_swap_cpp-master的example中的SubscribeCandlestickEvent的main.cpp中集成签名函数，对应的include 和函数实现如下：


#include <time.h&gt;
#include <openssl/hmac.h&gt;
#include "Signer.h"
#include "./Utils/base64.h"
#include <sstream&gt;


static std::string CreateSignature(const string&amp; method, const string&amp; host, const string&amp; path, const string&amp; para, const string&amp; secret_key)
{
&nbsp; stringstream msg_buf;
&nbsp; msg_buf << method << "\n"
&nbsp; &nbsp; << host << "\n"
&nbsp; &nbsp; << path << "\n"
&nbsp; &nbsp; << para;
&nbsp; string msg = msg_buf.str();


&nbsp; unsigned char hash[1024];
&nbsp; unsigned int len = 1024;


&nbsp; HMAC_CTX* pctx = HMAC_CTX_new();
&nbsp; HMAC_Init_ex(pctx, secret_key.c_str(), secret_key.length(), EVP_sha256(), NULL);
&nbsp; HMAC_Update(pctx, (unsigned char*)&amp;msg[0], msg.length());
&nbsp; HMAC_Final(pctx, hash, &amp;len);
&nbsp; HMAC_CTX_free(pctx);


&nbsp; string code;
&nbsp; code = base64_encode(hash, 32);


&nbsp; return code;
}
我的openssl 版本是 1.1.0，是支持HMAC方式签名的。
现在的问题是cmake编译不过，具体报错信息如下。在没实现签名函数前，编译example是成功的，可以正常接收到实时K线数据的。


Linking CXX executable SubscribeCandlestickEvent
CMakeFiles/SubscribeCandlestickEvent.dir/main.cpp.o：在函数‘main’中：
/home/asq/huobi_swap_Cpp-master/examples/SubscribeCandlestickEvent/main.cpp:(.text+0x42c1)：对‘HMAC_CTX_new’未定义的引用
/home/asq/huobi_swap_Cpp-master/examples/SubscribeCandlestickEvent/main.cpp:(.text+0x432a)：对‘HMAC_CTX_free’未定义的引用
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/SubscribeCandlestickEvent.dir/build.make:174：SubscribeCandlestickEvent] 错误 1
make[1]: *** [CMakeFiles/Makefile2:64：CMakeFiles/SubscribeCandlestickEvent.dir/all] 错误 2
make: *** [Makefile:76：all] 错误 2
